name: Android Build

on:
  push:
    #    branches: [ main ]
    tags: ["v*"]
  #  pull_request:
  #    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: |
          pnpm install

      - name: Setup Android signing - Capacitor
        run: |
          base64 -d <<< "${{ secrets.KEYSTORE_FILE }}" > ./android/media-hub-keystore.jks

      - name: Build Android Release
        if: github.event_name != 'pull_request'
        timeout-minutes: 20
        env:
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
        run: |
          pnpm build
          pnpm cap sync
          pnpm cap build android --androidreleasetype AAB
          pnpm cap build android --androidreleasetype APK

      - name: Upload AAB artifact (Release builds only)
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: android-app-bundle
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 30
        continue-on-error: false

      - name: Upload APK artifact (Release builds)
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: android/app/build/outputs/apk/release/app-release-signed.apk
          retention-days: 30
        continue-on-error: false

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: android-app-bundle

      # - name: Upload .aab to Google Play
      #   uses: KevinRohn/github-action-upload-play-store@v1.0.1
      #   with:
      #     service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #     package_name: "xyz.armaldio.mediahub.app"
      #     aab_file_path: "app-release-signed.aab"
      #     track: ${{ github.ref == 'refs/heads/main' && 'internal' || 'production' }}
      #     release_status: "completed"

      - name: Upload .aab to Google Play
        uses: KevinRohn/github-action-upload-play-store@v1.0.1
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: "xyz.armaldio.mediahub.app"
          aab_file_path: "app-release-signed.aab"
          track: internal
          release_status: "completed"

      # - name: Upload .aab to Google Play
      #   uses: KevinRohn/github-action-upload-play-store@v1.0.1
      #   with:
      #     service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #     package_name: "xyz.armaldio.mediahub.app"
      #     aab_file_path: "app-release-signed.aab"
      #     track: alpha
      #     release_status: "completed"

      # - name: Upload .aab to Google Play
      #   uses: KevinRohn/github-action-upload-play-store@v1.0.1
      #   with:
      #     service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #     package_name: "xyz.armaldio.mediahub.app"
      #     aab_file_path: "app-release-signed.aab"
      #     track: beta
      #     release_status: "completed"

      # - name: Upload .aab to Google Play
      #   uses: KevinRohn/github-action-upload-play-store@v1.0.1
      #   with:
      #     service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #     package_name: "xyz.armaldio.mediahub.app"
      #     aab_file_path: "app-release-signed.aab"
      #     track: rollout
      #     release_status: "completed"
